# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: webcast/model/message/ext.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "HotTag",
    "PopProduct",
    "TraceInfo",
    "WebcastOecLiveShoppingMessage",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from .....message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class HotTag(betterproto2.Message):
    product_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    hot_count: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message("webcast.model.message.ext", "HotTag", HotTag)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class PopProduct(betterproto2.Message):
    title: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    price: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    image_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    open_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    product_type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        5, betterproto2.TYPE_STRING
    )

    product_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(6, betterproto2.TYPE_INT64)
    )

    source: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    source_from: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(8, betterproto2.TYPE_INT32)
    )

    platform: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(10, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message(
    "webcast.model.message.ext", "PopProduct", PopProduct
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class TraceInfo(betterproto2.Message):
    operate_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    arrival_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    send_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message(
    "webcast.model.message.ext", "TraceInfo", TraceInfo
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class WebcastOecLiveShoppingMessage(betterproto2.Message):
    common: "___shared__message__.CommonMessageData | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    action_type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT32)
    )

    live_product_number: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT32
    )

    pop_product: "PopProduct | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    trace_info: "TraceInfo | None" = betterproto2.field(
        5, betterproto2.TYPE_MESSAGE, optional=True
    )

    hot_tags: "list[HotTag]" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, repeated=True
    )

    atmosphere_tag_info: "__message__.AtmosphereTagInfo | None" = betterproto2.field(
        7, betterproto2.TYPE_MESSAGE, optional=True
    )

    live_permission_info: "__message__.LivePermissionInfo | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True
    )

    pin_card_delay_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        10, betterproto2.TYPE_INT64
    )

    billboard_display_result: "__message__.BillboardDisplayResult | None" = (
        betterproto2.field(14, betterproto2.TYPE_MESSAGE, optional=True)
    )

    dispersion_info: "list[__message__.DispersionInfo]" = betterproto2.field(
        15, betterproto2.TYPE_MESSAGE, repeated=True
    )

    promotion_info: "__message__.PromotionInfo | None" = betterproto2.field(
        16, betterproto2.TYPE_MESSAGE, optional=True
    )

    refresh_live_bag_info: "__message__.RefreshLiveBagInfo | None" = betterproto2.field(
        19, betterproto2.TYPE_MESSAGE, optional=True
    )

    voucher: "__message__.Voucher | None" = betterproto2.field(
        21, betterproto2.TYPE_MESSAGE, optional=True
    )

    oec_live_shopping_message_v2: "__data__oec_msg__.OecLiveShoppingMessageV2 | None" = betterproto2.field(
        100, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.message.ext",
    "WebcastOecLiveShoppingMessage",
    WebcastOecLiveShoppingMessage,
)


from ....shared import message as ___shared__message__
from ... import message as __message__
from ...data import oec_msg as __data__oec_msg__
