# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: webcast/model/live_match.proto, webcast/model/live_match_battle_team_user_armies.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "AnchorMatchSettings",
    "BattleAbTest",
    "BattleAbTestList",
    "BattleAbTestSetting",
    "BattleBaseUserInfo",
    "BattleBonusConfig",
    "BattleComboInfo",
    "BattleEffect",
    "BattleEffectInfos",
    "BattleFeatureFlags",
    "BattlePrompt",
    "BattlePromptElem",
    "BattleRivalTag",
    "BattleTaskGiftAmountGuide",
    "BattleTeamResult",
    "BattleTeamUser",
    "BattleTeamUserArmies",
    "BattleUserInfo",
    "BestTeammateRelation",
    "CohostContentGuideInfo",
    "EnigmaBattleExtraInfo",
    "EnigmaBattleSetting",
    "GiftModeMeta",
    "HighScoreControlCfg",
    "LeagueScoreInfo",
    "MatchPunishEffectInfo",
    "MatchPunishExtraInfo",
    "PlaybookBizExtra",
    "PreviewPeriod",
    "RecommendedPlaybookInfo",
    "RewardPeriodConfig",
    "TaskPeriodConfig",
    "TeamMatchCampaign",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from .....message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class AnchorMatchSettings(betterproto2.Message):
    enable_ai_commentary: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "webcast.model.live.match", "AnchorMatchSettings", AnchorMatchSettings
)


@dataclass(eq=False, repr=False)
class BattleAbTest(betterproto2.Message):
    ab_test_type: "__data__.BattleAbTestType" = betterproto2.field(
        1, betterproto2.TYPE_ENUM, default_factory=lambda: __data__.BattleAbTestType(0)
    )

    group: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT32)
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleABTest", BattleAbTest
)


@dataclass(eq=False, repr=False)
class BattleAbTestList(betterproto2.Message):
    ab_test_list: "list[BattleAbTest]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleABTestList", BattleAbTestList
)


@dataclass(eq=False, repr=False)
class BattleAbTestSetting(betterproto2.Message):
    key: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    value: "BattleAbTestList | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleABTestSetting", BattleAbTestSetting
)


@dataclass(eq=False, repr=False)
class BattleBaseUserInfo(betterproto2.Message):
    user_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    nick_name: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    avatar_thumb: "__base__.ImageModel | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    display_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    room_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT64)
    )

    invitation_role: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        6, betterproto2.TYPE_INT32
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleBaseUserInfo", BattleBaseUserInfo
)


@dataclass(eq=False, repr=False)
class BattleBonusConfig(betterproto2.Message):
    preview_start_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT64
    )

    preview_config: "list[PreviewPeriod]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    target_config: "TaskPeriodConfig | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    reward_config: "RewardPeriodConfig | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    gift_amount_guide: "dict[int, BattleTaskGiftAmountGuide]" = betterproto2.field(
        5,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_INT64, betterproto2.TYPE_MESSAGE
        ),
    )

    preview_start_timestamp: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        6, betterproto2.TYPE_INT64
    )

    preview_click_action_schema_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleBonusConfig", BattleBonusConfig
)


@dataclass(eq=False, repr=False)
class BattleComboInfo(betterproto2.Message):
    user_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    combo_status: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    combo_count: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT64)
    )

    combo_icon_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        4, betterproto2.TYPE_STRING
    )

    combo_type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT32)
    )

    combo_rule_guide_schema: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        6, betterproto2.TYPE_STRING
    )

    user_id_str: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    combo_count_str: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        8, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleComboInfo", BattleComboInfo
)


@dataclass(eq=False, repr=False)
class BattleEffect(betterproto2.Message):
    type: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    uid_list: "list[typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]]" = betterproto2.field(
        2, betterproto2.TYPE_STRING, repeated=True
    )

    effect_extra: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleEffect", BattleEffect
)


@dataclass(eq=False, repr=False)
class BattleEffectInfos(betterproto2.Message):
    effect_info_list: "list[BattleEffect]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    effect_list_version: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_INT64
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleEffectInfos", BattleEffectInfos
)


@dataclass(eq=False, repr=False)
class BattleFeatureFlags(betterproto2.Message):
    enable_match_countdown_optimization: "bool" = betterproto2.field(
        1, betterproto2.TYPE_BOOL
    )

    hide_combo_count_on_start: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "webcast.model.live.match", "BattleFeatureFlags", BattleFeatureFlags
)


@dataclass(eq=False, repr=False)
class BattlePrompt(betterproto2.Message):
    prompt_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    elems: "list[BattlePromptElem]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattlePrompt", BattlePrompt
)


@dataclass(eq=False, repr=False)
class BattlePromptElem(betterproto2.Message):
    prompt_field: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    value: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattlePromptElem", BattlePromptElem
)


@dataclass(eq=False, repr=False)
class BattleRivalTag(betterproto2.Message):
    bg_image: "__base__.ImageModel | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    icon_image: "__base__.ImageModel | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    content: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleRivalTag", BattleRivalTag
)


@dataclass(eq=False, repr=False)
class BattleTaskGiftAmountGuide(betterproto2.Message):
    guide_prompt: "BattlePrompt | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    prompt_type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT32)
    )

    disappear_duration: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT32
    )

    icon_image: "__base__.ImageModel | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True
    )

    gift_image: "__base__.ImageModel | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )

    recommend_gift_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        21, betterproto2.TYPE_INT64
    )

    recommend_gift_count: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        22, betterproto2.TYPE_INT32
    )

    guide_content: "__message__common__.Text | None" = betterproto2.field(
        23, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleTaskGiftAmountGuide", BattleTaskGiftAmountGuide
)


@dataclass(eq=False, repr=False)
class BattleTeamResult(betterproto2.Message):
    team_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    team_user: "list[BattleTeamUser]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    result: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT32)
    )

    total_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )

    total_enigma_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        5, betterproto2.TYPE_INT64
    )

    total_enigma_uv: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        6, betterproto2.TYPE_INT64
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleTeamResult", BattleTeamResult
)


@dataclass(eq=False, repr=False)
class BattleTeamUser(betterproto2.Message):
    user_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    user_id_str: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        3, betterproto2.TYPE_STRING
    )

    enigma_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleTeamUser", BattleTeamUser
)


@dataclass(eq=False, repr=False)
class BattleTeamUserArmies(betterproto2.Message):
    team_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    team_user: "list[BattleTeamUser]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )

    team_total_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT64
    )

    user_armies: "__message__battle__.BattleUserArmies | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    host_rank: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT64)
    )

    team_total_enigma_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        6, betterproto2.TYPE_INT64
    )

    team_total_enigma_uv: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        7, betterproto2.TYPE_INT64
    )

    host_visible_rank_from_team_id: "dict[int, int]" = betterproto2.field(
        8,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_INT64, betterproto2.TYPE_INT64
        ),
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleTeamUserArmies", BattleTeamUserArmies
)


@dataclass(eq=False, repr=False)
class BattleUserInfo(betterproto2.Message):
    user: "BattleBaseUserInfo | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    tags: "list[BattleRivalTag]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BattleUserInfo", BattleUserInfo
)


@dataclass(eq=False, repr=False)
class BestTeammateRelation(betterproto2.Message):
    user_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    best_teammate_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_INT64
    )


default_message_pool.register_message(
    "webcast.model.live.match", "BestTeammateRelation", BestTeammateRelation
)


@dataclass(eq=False, repr=False)
class CohostContentGuideInfo(betterproto2.Message):
    recommended_battle_type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT32
    )


default_message_pool.register_message(
    "webcast.model.live.match", "CohostContentGuideInfo", CohostContentGuideInfo
)


@dataclass(eq=False, repr=False)
class EnigmaBattleExtraInfo(betterproto2.Message):
    has_started: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    is_gift_from_enigma: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "webcast.model.live.match", "EnigmaBattleExtraInfo", EnigmaBattleExtraInfo
)


@dataclass(eq=False, repr=False)
class EnigmaBattleSetting(betterproto2.Message):
    is_startable: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    enigma_battle_campaign_start: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        2, betterproto2.TYPE_INT64
    )

    enigma_battle_campaign_end: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT64
    )


default_message_pool.register_message(
    "webcast.model.live.match", "EnigmaBattleSetting", EnigmaBattleSetting
)


@dataclass(eq=False, repr=False)
class GiftModeMeta(betterproto2.Message):
    gift_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    gift_name_key: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )

    gift_icon_image: "__base__.ImageModel | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    gift_mode_desc: "__message__common__.Text | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "GiftModeMeta", GiftModeMeta
)


@dataclass(eq=False, repr=False)
class HighScoreControlCfg(betterproto2.Message):
    normal_control_applied: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    threshold: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    origin_display_to_user_list: "list[typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]]" = betterproto2.field(
        3, betterproto2.TYPE_INT64, repeated=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "HighScoreControlCfg", HighScoreControlCfg
)


@dataclass(eq=False, repr=False)
class LeagueScoreInfo(betterproto2.Message):
    estimated_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT64
    )

    is_opt_out: "bool" = betterproto2.field(2, betterproto2.TYPE_BOOL)

    is_activity_period: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)

    content_text: "__message__common__.Text | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )

    class_opt_out: "bool" = betterproto2.field(5, betterproto2.TYPE_BOOL)

    content_text_open: "__message__common__.Text | None" = betterproto2.field(
        6, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "LeagueScoreInfo", LeagueScoreInfo
)


@dataclass(eq=False, repr=False)
class MatchPunishEffectInfo(betterproto2.Message):
    user_to_effect_map: "dict[int, int]" = betterproto2.field(
        1,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_INT64, betterproto2.TYPE_INT64
        ),
    )

    effect_to_effect_struct_map: "dict[int, __data__.EffectStruct]" = (
        betterproto2.field(
            2,
            betterproto2.TYPE_MAP,
            map_meta=betterproto2.map_meta(
                betterproto2.TYPE_INT64, betterproto2.TYPE_MESSAGE
            ),
        )
    )


default_message_pool.register_message(
    "webcast.model.live.match", "MatchPunishEffectInfo", MatchPunishEffectInfo
)


@dataclass(eq=False, repr=False)
class MatchPunishExtraInfo(betterproto2.Message):
    match_punish_effect_info: "MatchPunishEffectInfo | None" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, optional=True
    )

    cohost_content_guide_info: "CohostContentGuideInfo | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    recommended_playbook_info: "RecommendedPlaybookInfo | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "MatchPunishExtraInfo", MatchPunishExtraInfo
)


@dataclass(eq=False, repr=False)
class PlaybookBizExtra(betterproto2.Message):
    custom_atomic_capabilities: "dict[str, str]" = betterproto2.field(
        1,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_STRING, betterproto2.TYPE_STRING
        ),
    )


default_message_pool.register_message(
    "webcast.model.live.match", "PlaybookBizExtra", PlaybookBizExtra
)


@dataclass(eq=False, repr=False)
class PreviewPeriod(betterproto2.Message):
    duration: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    prompt: "BattlePrompt | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )

    icon_image: "__base__.ImageModel | None" = betterproto2.field(
        25, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "PreviewPeriod", PreviewPeriod
)


@dataclass(eq=False, repr=False)
class RecommendedPlaybookInfo(betterproto2.Message):
    playbook_ids: "list[typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]]" = betterproto2.field(
        1, betterproto2.TYPE_INT64, repeated=True
    )

    playbook_biz_extras: "dict[int, PlaybookBizExtra]" = betterproto2.field(
        2,
        betterproto2.TYPE_MAP,
        map_meta=betterproto2.map_meta(
            betterproto2.TYPE_INT64, betterproto2.TYPE_MESSAGE
        ),
    )


default_message_pool.register_message(
    "webcast.model.live.match", "RecommendedPlaybookInfo", RecommendedPlaybookInfo
)


@dataclass(eq=False, repr=False)
class RewardPeriodConfig(betterproto2.Message):
    reward_start_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT64
    )

    duration: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    reward_multiple: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT32
    )

    reward_start_timestamp: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        4, betterproto2.TYPE_INT64
    )

    reward_prepare_prompt: "BattlePrompt | None" = betterproto2.field(
        11, betterproto2.TYPE_MESSAGE, optional=True
    )

    rewarding_prompt: "BattlePrompt | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )

    click_prompt: "BattlePrompt | None" = betterproto2.field(
        13, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.model.live.match", "RewardPeriodConfig", RewardPeriodConfig
)


@dataclass(eq=False, repr=False)
class TaskPeriodConfig(betterproto2.Message):
    target_start_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        1, betterproto2.TYPE_INT64
    )

    duration: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    target_start_timestamp: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        3, betterproto2.TYPE_INT64
    )

    click_action: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(11, betterproto2.TYPE_INT32)
    )

    click_prompt: "BattlePrompt | None" = betterproto2.field(
        12, betterproto2.TYPE_MESSAGE, optional=True
    )

    prompt_type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(21, betterproto2.TYPE_INT32)
    )

    static_prompt: "BattlePrompt | None" = betterproto2.field(
        22, betterproto2.TYPE_MESSAGE, optional=True
    )

    progress_target: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        23, betterproto2.TYPE_INT64
    )

    target_type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(24, betterproto2.TYPE_INT32)
    )

    icon_image: "__base__.ImageModel | None" = betterproto2.field(
        25, betterproto2.TYPE_MESSAGE, optional=True
    )

    click_action_schema_url: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        26, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.model.live.match", "TaskPeriodConfig", TaskPeriodConfig
)


@dataclass(eq=False, repr=False)
class TeamMatchCampaign(betterproto2.Message):
    best_teammate_relation: "list[BestTeammateRelation]" = betterproto2.field(
        1, betterproto2.TYPE_MESSAGE, repeated=True
    )

    start_sfx_team_id: "list[typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]]" = betterproto2.field(
        2, betterproto2.TYPE_INT64, repeated=True
    )

    has_team_match_mvp_sfx: "bool" = betterproto2.field(3, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "webcast.model.live.match", "TeamMatchCampaign", TeamMatchCampaign
)


from ... import base as __base__
from ... import data as __data__
from ...message import battle as __message__battle__
from ...message import common as __message__common__
