# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: webcast/shared/message.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "CommonMessageData",
    "LiveMessageId",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class CommonMessageData(betterproto2.Message):
    method: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    msg_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    room_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(3, betterproto2.TYPE_INT64)
    )

    create_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )

    monitor: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT32)
    )

    is_show_msg: "bool" = betterproto2.field(6, betterproto2.TYPE_BOOL)

    describe: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        7, betterproto2.TYPE_STRING
    )

    display_text: "__model__message__common__.Text | None" = betterproto2.field(
        8, betterproto2.TYPE_MESSAGE, optional=True
    )

    anchor_fold_type: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        10, betterproto2.TYPE_INT64
    )

    msg_process_filter_v: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        14, betterproto2.TYPE_STRING
    )

    from_idc: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        15, betterproto2.TYPE_STRING
    )

    to_idc: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        16, betterproto2.TYPE_STRING
    )

    depend_root_id: "LiveMessageId | None" = betterproto2.field(
        19, betterproto2.TYPE_MESSAGE, optional=True
    )

    anchor_priority_score: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        21, betterproto2.TYPE_INT64
    )

    room_message_heat_level: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        22, betterproto2.TYPE_INT64
    )

    fold_type_for_web: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        23, betterproto2.TYPE_INT64
    )

    client_send_time: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = betterproto2.field(
        25, betterproto2.TYPE_INT64
    )

    dispatch_strategy: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = betterproto2.field(
        26, betterproto2.TYPE_INT32
    )


default_message_pool.register_message(
    "webcast.shared.message", "CommonMessageData", CommonMessageData
)


@dataclass(eq=False, repr=False, config={"extra": "forbid"})
class LiveMessageId(betterproto2.Message):
    primary_id: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        1, betterproto2.TYPE_STRING
    )

    message_scene: "typing.Annotated[str, pydantic.AfterValidator(betterproto2.validators.validate_string)]" = betterproto2.field(
        2, betterproto2.TYPE_STRING
    )


default_message_pool.register_message(
    "webcast.shared.message", "LiveMessageID", LiveMessageId
)


from ...model.message import common as __model__message__common__
