# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: webcast/envelope_model.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "EnvelopeEnigmaInfo",
    "EnvelopeGift",
    "EnvelopeReward",
    "EnvelopeRewardPool",
)

import typing

import betterproto2
import pydantic
from pydantic.dataclasses import dataclass

from ....message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class EnvelopeEnigmaInfo(betterproto2.Message):
    is_enigma_mask_on: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)


default_message_pool.register_message(
    "webcast.envelope.model", "EnvelopeEnigmaInfo", EnvelopeEnigmaInfo
)


@dataclass(eq=False, repr=False)
class EnvelopeGift(betterproto2.Message):
    gift_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT64)
    )

    gift_price: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    gift_name: "__model__message__common__.Text | None" = betterproto2.field(
        3, betterproto2.TYPE_MESSAGE, optional=True
    )

    gift_image: "__model__base__.ImageModel | None" = betterproto2.field(
        4, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message(
    "webcast.envelope.model", "EnvelopeGift", EnvelopeGift
)


@dataclass(eq=False, repr=False)
class EnvelopeReward(betterproto2.Message):
    type: "typing.Annotated[int, pydantic.Field(ge=-2**31, le=2**31 - 1)]" = (
        betterproto2.field(1, betterproto2.TYPE_INT32)
    )

    count: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(2, betterproto2.TYPE_INT64)
    )

    gift_id: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(4, betterproto2.TYPE_INT64)
    )

    price: "typing.Annotated[int, pydantic.Field(ge=-2**63, le=2**63 - 1)]" = (
        betterproto2.field(5, betterproto2.TYPE_INT64)
    )


default_message_pool.register_message(
    "webcast.envelope.model", "EnvelopeReward", EnvelopeReward
)


@dataclass(eq=False, repr=False)
class EnvelopeRewardPool(betterproto2.Message):
    rewards: "list[EnvelopeReward]" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, repeated=True
    )


default_message_pool.register_message(
    "webcast.envelope.model", "EnvelopeRewardPool", EnvelopeRewardPool
)


from ...model import base as __model__base__
from ...model.message import common as __model__message__common__
